version: '3.4'

services:
  myapp: 
    image: myapp
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    links: 
      - mongodb
  mongodb: 
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
  